# Generated by Django 3.2.22 on 2023-11-05 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0002_auto_20231104_1726'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evento',
            name='reserva',
            field=models.ManyToManyField(related_name='reserva_evento', through='hotel.ReservaEvento', to='hotel.Reserva'),
        ),
    ]
